"""Game final_points column

Revision ID: 2ada84c511ed
Revises: ba0c9799c8d2
Create Date: 2023-01-15 11:17:21.757472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ada84c511ed'
down_revision = 'ba0c9799c8d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('final_points', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_column('final_points')

    # ### end Alembic commands ###
