"""start8

Revision ID: 7273cc072c22
Revises: 
Create Date: 2022-12-26 22:26:58.356557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7273cc072c22'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artist_id'), ['id'], unique=False)

    op.create_table('img',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sm', sa.Text(), nullable=False),
    sa.Column('md', sa.Text(), nullable=False),
    sa.Column('lg', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('img', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_img_id'), ['id'], unique=False)

    op.create_table('owner',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('owner', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_owner_id'), ['id'], unique=False)

    op.create_table('album',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('img_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['img_id'], ['img.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('album', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_album_id'), ['id'], unique=False)

    op.create_table('playlist',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('snapshot_id', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('owner_id', sa.Text(), nullable=True),
    sa.Column('img_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['img_id'], ['img.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['owner.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('playlist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_playlist_id'), ['id'], unique=False)

    op.create_table('album_artist',
    sa.Column('album_id', sa.Text(), nullable=False),
    sa.Column('artist_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['album.id'], ),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], ),
    sa.PrimaryKeyConstraint('album_id', 'artist_id')
    )
    op.create_table('track',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('album_id', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('prev_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['album_id'], ['album.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('track', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_track_id'), ['id'], unique=False)

    op.create_table('playlist_track',
    sa.Column('playlist_id', sa.Text(), nullable=False),
    sa.Column('track_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlist.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['track.id'], ),
    sa.PrimaryKeyConstraint('playlist_id', 'track_id')
    )
    op.create_table('track_artist',
    sa.Column('track_id', sa.Text(), nullable=False),
    sa.Column('artist_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['track.id'], ),
    sa.PrimaryKeyConstraint('track_id', 'artist_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('track_artist')
    op.drop_table('playlist_track')
    with op.batch_alter_table('track', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_track_id'))

    op.drop_table('track')
    op.drop_table('album_artist')
    with op.batch_alter_table('playlist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_playlist_id'))

    op.drop_table('playlist')
    with op.batch_alter_table('album', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_album_id'))

    op.drop_table('album')
    with op.batch_alter_table('owner', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_owner_id'))

    op.drop_table('owner')
    with op.batch_alter_table('img', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_img_id'))

    op.drop_table('img')
    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artist_id'))

    op.drop_table('artist')
    # ### end Alembic commands ###
