"""quest pk track -> q_num

Revision ID: d1076770cbe8
Revises: 
Create Date: 2023-01-03 23:09:36.973625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1076770cbe8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=True),
    sa.Column('playlist_id', sa.Text(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlist.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_game_user_id'), ['user_id'], unique=False)

    op.create_table('quest',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Text(), nullable=True),
    sa.Column('q_num', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['track.id'], ),
    sa.PrimaryKeyConstraint('game_id', 'q_num')
    )
    with op.batch_alter_table('quest', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quest_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quest_track_id'), ['track_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quest', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quest_track_id'))
        batch_op.drop_index(batch_op.f('ix_quest_game_id'))

    op.drop_table('quest')
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_user_id'))
        batch_op.drop_index(batch_op.f('ix_game_id'))

    op.drop_table('game')
    # ### end Alembic commands ###
